### PR TITLE
Plugin: Git revision date localized plugin added

### PR DESCRIPTION
**Pull request by TOTON95**
This PR starts adding plugins listed in #43, specifically `mkdocs-git-revision-date-localized-plugin`.

Suggestions/Corrections are very welcomed.

### CODE REVIEW

**Review by knmcguire — COMMENTED** [review]
Hi and thanks! Very nice addition.

 Currently it says 11th of June as last updated date, but I guess there is no way around it since this includes an actual update. I'm trying to think how to solve that but probably no easy solution for that...

**Comment by TOTON95** [comment]
> Hi and thanks! Very nice addition.
> 
> Currently it says 11th of June as last updated date, but I guess there is no way around it since this includes an actual update. I'm trying to think how to solve that but probably no easy solution for that...

Yes @knmcguire, that's unfortunately the problem if included directly. I am currently studying the override of themes for mkdocs, and see if that helps since it would be some sort of "include" rather than direct insertion/actual update.

Let me see how it goes, and if it works, I think it might help the goatcounter insertion as well.

**Comment by knmcguire** [comment]
Alright, I'll wait for that then. thanks!

I haven't completely figured out how to do that in a nice and clean way either then providing the full adjusted theme in source and I don't think that's a good approach.

**Comment by knmcguire** [comment]
have you looked at this recently? We can also just consider just to merge it and be okay with this one time the date being different as a starting point. I don't mind that much personally

**Comment by knmcguire** [comment]
I'll just merge this :)

**Comment by TOTON95** [comment]
@knmcguire Thank you, sorry I completely forgot about this one 😓

**Comment by knmcguire** [comment]
No worries! I was planning a huge double check of all the links on the web anyway :) so it would have been accurate anyway haha

**Comment by knmcguire** [comment]
I've added you as a reviewer to those but it's a big one.. perhaps it's good to just merge them and add a CI check for the links

**Pull request merged**
