### PR TITLE
Trying out website in MKdocs 

### PR DESCRIPTION
**Pull request by knmcguire**
A colleague of mine pointed me to [mkdocs](https://www.mkdocs.org/), which worked out nicely! 

To try it out for yourself:
* checkout this branch (`mkdocs-tryout2`) 
* `pip3 install mkdocs pymdown-extensions `
* Serve it locally with `mkdocs serve`

Here are some screenshots with the readthedoc theme :)

image
image

### CODE REVIEW

**Comment by knmcguire** [comment]
The website of this PR is hosted on https://ros-aerial.github.io/aerial_robotic_landscape/. Please check it out and let me know if I can merge this!

**Comment by TOTON95** [comment]
@knmcguire Sure, count with it. I've been looking to some plugins that we can add to it as well, with interesting outputs.

**Comment by knmcguire** [comment]
Ah nice! 

You can either propose it here or we can finish this as a base and add prs for any additional plugins.

**Comment by TOTON95** [comment]
Looks good! Thanks!

**Review by TOTON95 — APPROVED** [review]

**Pull request merged**
