### PR TITLE
Update links 18th of November

### PR DESCRIPTION
**Pull request by knmcguire**
There are quite some deadlinks in the aerial robotics landscape so let's update it!

### CODE REVIEW

**Comment by knmcguire** [comment]
This one is quite big.... and I've also pruned some stuff here and there. 

I think it would be more suitable to add a CI to this to check the links but that's a different PR

**Comment by TOTON95** [comment]
> This one is quite big.... and I've also pruned some stuff here and there.
> 
> I think it would be more suitable to add a CI to this to check the links but that's a different PR

I see, we can start with the request's result and see if we get 404'ed, I'm not sure how we can handle redirections though

**Comment by TOTON95** [comment]
@knmcguire  let me see if I can add https://pypi.org/project/mkdocs-linkcheck/ to this PR

**Comment by TOTON95** [comment]
> Go for it! I think you should have access to this branch as well

@knmcguire Yes, I have access to the branch, yesterday I was doing some tests, and I might resume tonight

**Comment by knmcguire** [comment]
I've opened up a ticket for it in #71, but yes I agree let's use it manually for now. Thanks for trying it out!

I'll merge the branch as is, but at least we got the most of it.

**Comment by TOTON95** [comment]
Sounds good, following the process in #71

**Pull request merged**
