### PR TITLE
add useful vi/vo datasets to the aerial autonomy VIO package information

### PR DESCRIPTION
**Pull request by dirksavage88**
Add useful dataset links for visual (inertial) odometry testing. Some datasets target aerial vehicles but others different platforms. Datasets come in different formats with exception to the google drive link which should purely be ros2 bag files for ease of use.

### CODE REVIEW

**Review by botmayank — APPROVED** [review]
lgtm! Thanks for getting these in one place :smile:

**Comment by botmayank** [comment]
@dirksavage88  feel free to make the changes you mentioned and you can re-request a review or @knmcguire can approve for merge as well but overall the section etc looks good to me

**Comment by TOTON95** [comment]
@dirksavage88 @knmcguire I took the opportunity to add one more to reduce the number of PRs

**Review by knmcguire — APPROVED** [review]
@TOTON95 Ah yes thanks for that addition! I was just thinking of that one because of their RSS workshop.

And thanks @dirksavage88 for these additions. This is super helpful!

**Pull request merged**
