### PR TITLE
Autopilot list add

### PR DESCRIPTION
**Pull request by knmcguire**
Just a list of available autopilots :)

### CODE REVIEW

**Comment by gajena** [comment]
It looks good if we look at it from an active project point of view.
Though there are one or two projects that are somewhat active but maybe not as famous as others (I have only used Crazyflie, PX4, Ardupilot):-
* [ROSflight](https://github.com/rosflight)
* [Cleanflight](https://github.com/cleanflight):- from a little bit of information, Betaflight is a kind of superset of Cleanflight.

**Comment by knmcguire** [comment]
Hi! thanks for replying!

I'm indeed aware that betaflight spun off or something like that from cleanflight, but since it seems to have no active support no more, so I'm reluctant to put it in the list for now as an option for people to get started with. I guess people will find it anyway when they look into betaflight, but perhaps with a next PR we can add some text per autopilot to explain it more in detail, and then we can mention cleanflight there?

About the dji autopilot, we should indeed mention that here! It is a bit difficult to link to source code as it is not open, so let me see how I can add that to the list.

Good one on the ROSflight! This is the first time I've heard it but it should totally be on there. Seems to be just a few years old and meant to be as a very minimal autopilot (so less about supporting as many vehicles as possible, but just providing a solid base). I'll need to look into this one

Thanks! I'll update the list accordingly 😄

**Comment by gajena** [comment]
I agree. It will be better to expand things later if required, and there is a lot of autopilot software on the FPV side, so mentioning everything here does not make sense.
The developer page is a good go-to location for DJI products. Anyways, they also have a GitHub page for [SDK](https://github.com/dji-sdk/Onboard-SDK-ROS)

**Comment by knmcguire** [comment]
Thanks! I've just added the github repo for the sdk, so I'll merge it now.

**Pull request merged**
