### PR TITLE
Create a list of simulators for aerial robotics

### PR DESCRIPTION
**Pull request by knmcguire**
Here a list of links of some common aerial robotics simulators. It's a nice start and at one point it might be nice to show an comparison, but as a start I think this is enough.

### CODE REVIEW

**Comment by gajena** [comment]
Simulator mentioned here heavily focused on quad-rotor, but there are other flight simulator that focuses on flight dynamics for fw:-
* [JSBSim](https://github.com/JSBSim-Team/jsbsim) available support in PX4 and Ardupilot
* [FlightGear](https://www.flightgear.org/) available support in PX4 and Ardupilot, also provide different physics engine back-end including JSBSim
* [XPlane](https://www.x-plane.com/) provides interface to connect like [this](https://ardupilot.org/dev/docs/sitl-with-xplane.html)

Isaac sim based pkg:-
* [Pegasus](https://pegasussimulator.github.io/PegasusSimulator/source/setup/installation.html)

**Comment by knmcguire** [comment]
Ah yes, I'll add those as well!

Maybe we should make a new category based on flight dynamic model simulators? JSBsim seems that is able to model the dynamics but I can't see if it has a renderer as is one of the requirements of the first list. (perhaps I should call that list 'full simulators' or something). Flightgear and xplane does seem to fit in that first category as they do provide rendering. Flightgear also has a plugin for JSBsim for the dynamics.

**Comment by gajena** [comment]
I think mentioning JSBSim with simulators should be enough since it does provide ways to connect with Unreal Engine and FlightGear. Or mentioning JSBSim with Flightgear should suffice.

**Comment by knmcguire** [comment]
Done! Worth note that I mostly saw a lot of pilot training examples with flightgear and xplane but I have seen some papers that used those simulators for UAV flights as well.

I still made a separate section for flight dynamic models, currently only listing those I've seen in Flightgear, but it would be good to look up some more examples on these in the future.

Thanks! I'll merge it now as is.

**Pull request merged**
